### ISSUE TITLE
Why field of type array of objects returns first items only

### ISSUE THREAD

**Issue by appasahebs** [graphql-compose/graphql-compose-elasticsearch#106]
Why field of type array of objects returns first items only.

This is doc...
_source:{“terms":{"category":[{"term_id":726,"slug":"a","name":"aa"}, {"term_id":728,"slug":"b","name":"bb"}, {"term_id":729,"slug":"c","name":"cc"}]}}

Result is ...
_source:{“terms":{"category":{"term_id":726,"slug":"a","name":"aa"}}}

Not sure why b and c items not been picked. Used same index mapping from elasticsearch

**Comment by nodkz** [comment]
Try to use
```
const UserTC = composeWithElastic({
  ...
  pluralFields: ['terms.category'], 
  OR
  pluralFields: ['category'], 
});
```

I don't remember what exactly will work.

**Comment by appasahebs** [comment]
> Try to use
> 
> ```
> const UserTC = composeWithElastic({
>   ...
>   pluralFields: ['terms.category'], 
>   OR
>   pluralFields: ['category'], 
> });
> ```
> 
> I don't remember what exactly will work.

Awesome, thanks very much! @nodkz
