### ISSUE TITLE
Authentication and structured data

### ISSUE THREAD

**Issue by stoffern** [graphql-compose/graphql-compose-elasticsearch#31]
Hi,

Long time.. i am back online after moving from CPH to Norway... 😉 

I guess this is a question that has been asked before, but there is a reason why this is seperate.
Straight to the case:
I want to build a open source system that uses graphql compose and elasticsearch in background as datastore. Sanity uses some of the basics of what i wanna build here:
https://github.com/sanity-io/sanity (Headless CMS on mongodb)

Is there a way to setup authentication on tables or cloumns (dont know what it is called in elasticsearch). Is it also possible to set the structure of the database, or can the user create what he wants?

hope that is clear enough 😉 

cc @nodkz

**Comment by stoffern** [comment]
@nodkz any advices? ;)

**Comment by nodkz** [comment]
Sorry, i missed your question.

Elasticsearch has `index` and `types` as a collection in mongodb (cause you may have different algorithms for indexing, eg one type for users, other type for admins).

As a schema description of index/type the use `mappings`. So these mappings can be built on user side. You may add new fields in your mappings. But CANNOT modify existed fields types, for this you need create a new `type` and reindex all data from scratch from some other source.

Take a look at their basic concepts:
https://www.elastic.co/guide/en/elasticsearch/reference/current/_basic_concepts.html

Elastic does not provide any access restrictions per indexes. So proper checks should be done in your app. So it may be very costly to spin up db for every user, for obtaining proper isolation of users data.

Elastic is good enough and fast in a search. But for speed and tooling, you get quite uncomfortable conditions when you use elastic as a database.

**Comment by stoffern** [comment]
in other words, you recommend using mongodb like databases, instead of elastic. and elastic for more complex needs?

**Comment by nodkz** [comment]
Mongodb for storing data. Elastic for searching.
Of course you may use elastic for storing data, but i think you'll meet with a bunch of crazy problems, which already solved in mongo. In other hand, mongo has the worst text search.

Anyway, they are different tools for different tasks. Mongo mostly for data persistence, elastic mostly for searching.

**Comment by stoffern** [comment]
👍 nice to know, thanks for the info 😉
