### ISSUE TITLE
Is there a way to make a field required in the ElasticSearch mapping?

### ISSUE THREAD

**Issue by mflores-verys** [graphql-compose/graphql-compose-elasticsearch#40]
In the example [here](https://github.com/graphql-compose/graphql-compose-elasticsearch#typecomposer-from-elastic-mapping), the mapping specifies fields which can be provided. Is there a way to make a field required, such that not supplying a field would cause an error to be thrown?

**Comment by nodkz** [comment]
Yes, it possible. You need to call helper methods for generated types.

By default, you use standard Resolver in such way:
```js
const Schema = new GraphQLSchema({
  query: new GraphQLObjectType({
    name: 'Query',
    fields: {
      user: UserTC.getResolver('search').getFieldConfig(),
    },
  }),
});
```

But you may modify it before using in schema via 1) [Resolver args-methods](https://graphql-compose.github.io/docs/en/api-Resolver.html#args-methods) and 2) [InputType field-methods for complex objects](https://graphql-compose.github.io/docs/en/api-InputTypeComposer.html#field-methods) in such way
```js
const SearchResolver = UserTC.getResolver('search');

// 1) for top-level args
SearchResolver.makeRequired(['limit', 'skip']);

// 2) for nested args (some field inside InputObjectType)
const AggsInputType = SearchResolver.getArgTC('aggs');
AggsInputType.makeFieldNonNull('someSubField');

const Schema = new GraphQLSchema({
  query: new GraphQLObjectType({
    name: 'Query',
    fields: {
      user: SearchResolver.getFieldConfig(),
    },
  }),
});
```

**Comment by mflores-verys** [comment]
@nodkz that works perfectly, thank you. Let me know if you'd be open to a PR adding supporting documentation for this use case. :)

**Comment by nodkz** [comment]
Will be awesome!
Feel free to make any changes
