### ISSUE TITLE
example with addFields

### ISSUE THREAD

**Issue by lfender6445** [graphql-compose/graphql-compose-elasticsearch#41]
I am trying to use addFields on my EsTC object, but the data comes up as empty object - could you provide an example of addFields in your documentation? 

```
const ListingTypeComposer = composeWithElastic({
  elasticClient,
  elasticIndex,
  elasticMapping,
  elasticType,
  graphqlTypeName,
})

ListingTypeComposer.addFields({
  address: {
    type: GraphQLString,
    resolve: (source) => {
      console.log('here is the source', source)
      // above, source returns as {}
      // even though data is coming back in my ListingTypeComposer.resolve
      return source.addressLine1
    }
  },
})
```

If you could provide a working example in the readme of how addField can be used on top of graphql-compose-elasticsearch id really appreciate it

**Comment by nodkz** [comment]
Try to modify needed Type inside Resolver:
```js
// ListingTypeComposer.getResolver('search').getTypeComposer().getFieldTC('hits').addFields({
// shortand
ListingTypeComposer.get('$search.hits').addFields({
  address: {
    type: 'String', //   <--- use short syntax, graphql-compose understood such things
    resolve: (source) => {
      console.log('here is the source', source)
      // above, source returns as {}
      // even though data is coming back in my ListingTypeComposer.resolve
      return source.addressLine1
    }
  },
})
```

In this example we get `search` resolver, then take its output type as TypeComposer object, then step down to `hits` field (which will have elasticsearch row data) and modify this field type by addin to it `address` field.

**Comment by lfender6445** [comment]
Thanks for the quick response. Ill try this out and update the issue if it works!

**Comment by nodkz** [comment]
Just remove this fields from your type:
```js
ListingTypeComposer.get('$search.hits').removeField(['semtollfree', 'webtollfree'])
```

How I remember elastic returns completely all fields for `hits.source`. If it not happens (you will get empty data for your `desktopPhone` field. You may try to use `projection` property for requiring needed fields (request fields from db in programattic way if `desktopPhone` field present in query):
```js
export const desktopPhone = {
  type: 'String',
  resolve: (source: any, args: { isSem?: boolean } = {}) => {
    return args.isSem
      ? source.semtollfree
      : source.webtollfree
  },
  args: {
    isSem: { type: 'Boolean' },
  },
  projection: {
    semtollfree: true,
    webtollfree: true,
  }
}
```

Hope this will work.

**Comment by lfender6445** [comment]
@nodkz thank you so much for your work and your responses. they have been very helpful
