### ISSUE TITLE
Add automatic mapping fetching from "composeWithElastic" method

### ISSUE THREAD

**Issue by thejibz** [graphql-compose/graphql-compose-elasticsearch#46]
Use the elastic client connection or another mean to do a /[index]/_mapping/[type] GET call on the ES server and then use the mapping returned instead of manually fetching it.

I will fork the project and propose a pull request.

**Comment by nodkz** [comment]
Will be great. But do it like a helper function.

The main problem that this is async operation. But most schemas build in sync way. So in such way need to tune a server launch. Something like https://github.com/graphql-compose/graphql-compose-json#building-schema-asynchronously
