### ISSUE TITLE
Restrict available queries and add fields to input

### ISSUE THREAD

**Issue by janus-reith** [graphql-compose/graphql-compose-elasticsearch#70]
As an additional security measure, I'd like to only expose certain `elasticsearch` functionality over `graphql`, mostly `msearch`.

Also, my data contains a field `isVisible`. I only want to list entries that contain `isVisible: true`.
As I can't trust clients to always use that field I thought about adding it to the query on the server.

Would these two things be easy to achieve with this library? I'd appreciate feedback and if possible suggestions on how to implement that. :)

Third thing I just noticed: I only want to perform authorization on the server and provided `host` there to `elasticApiFieldConfig`.
That information is send to the client when I inspect my schema:

```
elastic50(
host: String = "http://user:password@urlt:9200"
): ElasticAPI50
```
Is there a simply way to prevent that?

**Comment by nodkz** [comment]
### Removing fields from API wrapper

```js
import { schemaComposer } from 'graphql-compose';

const fieldConfig = elasticApiFieldConfig(
        // you may provide existed Elastic Client instance
        new elasticsearch.Client({
          host: 'http://localhost:9200',
          apiVersion: '5.0',
        })
      );
const clientTC = schemaComposer.createOTC(fieldConfig.type);
clientTC.removeOtherFields('msearch'); // will remove all fields except `msearch`
const newFieldConfig = {
  ...fieldConfig,
  type: clientTC.getType();
};

const schema = new GraphQLSchema({
  query: new GraphQLObjectType({
    name: 'Query',
    fields: {
      elastic50: newFieldConfig,
    },
  }),
});
```
### Wrapping some method
`clientTC` from example above:
```js
const msearchResolveFn = clientTC.getFieldConfig('msearch').resolve;
const wrappedMsearch = (source, args, context, info) => {
  // somehow change args to adding `isVisible: true`
  // maybe need change args.body or another arg (need to investigate)
  return msearchResolveFn(source, args, context, info);
};
clientTC.extendField('msearch', { resolve: wrappedMsearch });
```

### Removing fields if you use Mappings:
```js
const UserTC = composeWithElastic({
  graphqlTypeName: 'UserES',
  elasticIndex: 'user',
  elasticType: 'user',
  elasticMapping: mapping,
  elasticClient: new elasticsearch.Client({
    host: 'http://localhost:9200',
    apiVersion: '5.0',
    log: 'trace',
  }),
  // elastic mapping does not contain information about is fields are arrays or not
  // so provide this information explicitly for obtaining correct types in GraphQL
  pluralFields: ['skills', 'languages'],
});

UserTC.removeOtherFields('msearch'); // will remove all fields except `msearch`
```

**Comment by janus-reith** [comment]
Awesome, thanks for the quick and detailed response!

**Comment by nodkz** [comment]
```diff
- schemaComposer.createOTC
+ schemaComposer.createObjectTC
```

`createOTC` method does not exist.

Anyway you may modify generated types as you with `graphql-compose`. See Api: https://graphql-compose.github.io/docs/api/ObjectTypeComposer.html

**Comment by janus-reith** [comment]
Great, just tried it out and removing fields from API wrapper worked as expected!

Now only `msearch`  is exposed, and it seems like this also solved my third issue about credentials being exposed, as now there is no suggested Host field anymore - Did I get that right, or might there be another place where that information is exposed in the schema?

**Comment by nodkz** [comment]
Only what you see in the schema introspection (or via GraphiQL/Playground docs) will be exposed. All other fields and arguments will not be exposed.

As the code above you may remove:
- any fields via [removeField()](https://graphql-compose.github.io/docs/api/ObjectTypeComposer.html#removefield) 
- and arguments via new just added method in graphql-compose@7.3.0 [removeFieldArg()](https://graphql-compose.github.io/docs/api/ObjectTypeComposer.html#removefieldarg)

**Comment by janus-reith** [comment]
Thank you, closing this.
