### ISSUE TITLE
vulnerabilities with dox, lodash

### ISSUE THREAD

**Issue by rajarameshvarma** [graphql-compose/graphql-compose-elasticsearch#75]
I am trying to install this package and npm is indicating three vulnerabilities (1 low and 2 high severity). They seem to be originating from lodash which is a dependency for dox. Anyway to avoid them?

**Comment by nodkz** [comment]
It should be fixed `dox` package.
Nothing to do in this repo right now.
Please reopen the issue when `dox` package will be updated.

Thanks.
