### ISSUE TITLE
Fetch Elastic Mapping does not work with Aliases

### ISSUE THREAD

**Issue by pcasa** [graphql-compose/graphql-compose-elasticsearch#92]
If an Alias for an Index is passed in, the Mapping will not work.

Looks like culprit is this line https://github.com/graphql-compose/graphql-compose-elasticsearch/blob/f6bc025e67a6e2a57d43086de641b23b8ad01bf7/src/utils.js#L123

Could be changed to something like 
```
const elasticMapping = await opts.elasticClient.indices.getMapping({
    index: opts.elasticIndex,
    type: opts.elasticType,
  });

const baseIndex = elasticMapping[opts.elasticIndex] || elasticMapping[Object.keys(elasticMapping)[0]];

return baseIndex.mappings[opts.elasticType];
```

**Comment by nodkz** [comment]
Please open PR with provided solution. I'll merge it. Tnx.
