### ISSUE TITLE
Is there an option for adding Term fields

### ISSUE THREAD

**Issue by pcasa** [graphql-compose/graphql-compose-elasticsearch#95]
First, Amazing project.  It's helped me tremendously, so thank you!

We have several ES Clusters that are pre 6.x versions.
Several indexes have the old `type: "string", index: "not_analyzed"` for fields we would like to run Aggs on.

Based on `getTermFields` function, it is looking for `keyword` for string fields.

Is there a way we can add fields to the Terms Rule?

**Comment by nodkz** [comment]
Honestly, I don't know. This project was used 2 years ago for some project. And for now, I'm not working with elastic. I just keep this package in sync with graphql-compose and nothing more. 

Feel free to send a pull request with the new features. I will happy to merge really useful improvements or fixes.

**Comment by pcasa** [comment]
Understood.
For now, will override the returned mapping changing the field type.
